// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFzdtdNNdI4Gj0jqwnvDPPbNRI7wYKRsk',
    appId: '1:83262491589:web:16005ea433f3b9cb4e59ac',
    messagingSenderId: '83262491589',
    projectId: 'teknofest-821a6',
    authDomain: 'teknofest-821a6.firebaseapp.com',
    storageBucket: 'teknofest-821a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmT7YPPudw0jBFHEdWsrDQ9KAFNRieuY8',
    appId: '1:83262491589:android:b55b7b695e8655174e59ac',
    messagingSenderId: '83262491589',
    projectId: 'teknofest-821a6',
    storageBucket: 'teknofest-821a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31xUZ32erVwUqO1LN66hbYx3DZNCd1CQ',
    appId: '1:83262491589:ios:75eb6942f007376f4e59ac',
    messagingSenderId: '83262491589',
    projectId: 'teknofest-821a6',
    storageBucket: 'teknofest-821a6.firebasestorage.app',
    iosBundleId: 'com.example.teknofestproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31xUZ32erVwUqO1LN66hbYx3DZNCd1CQ',
    appId: '1:83262491589:ios:75eb6942f007376f4e59ac',
    messagingSenderId: '83262491589',
    projectId: 'teknofest-821a6',
    storageBucket: 'teknofest-821a6.firebasestorage.app',
    iosBundleId: 'com.example.teknofestproje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFzdtdNNdI4Gj0jqwnvDPPbNRI7wYKRsk',
    appId: '1:83262491589:web:ab51fe032ef354184e59ac',
    messagingSenderId: '83262491589',
    projectId: 'teknofest-821a6',
    authDomain: 'teknofest-821a6.firebaseapp.com',
    storageBucket: 'teknofest-821a6.firebasestorage.app',
  );
}